import { CreateNewsSourceSchema } from "@acme/db/schema";

const sourceCandidates = [
  {
    name: "OpenAI News",
    slug: "openai-news",
    homepageUrl: "https://openai.com/news/",
    feedUrl: "https://openai.com/news/rss.xml",
    sourceType: "vendor_blog",
    credibility: 95,
    isActive: true,
  },
  {
    name: "Anthropic News",
    slug: "anthropic-news",
    homepageUrl: "https://www.anthropic.com/news",
    feedUrl: "https://www.anthropic.com/news/rss.xml",
    sourceType: "vendor_blog",
    credibility: 95,
    isActive: true,
  },
  {
    name: "Google AI Blog",
    slug: "google-ai-blog",
    homepageUrl: "https://blog.google/technology/ai/",
    feedUrl: "https://blog.google/technology/ai/rss/",
    sourceType: "vendor_blog",
    credibility: 90,
    isActive: true,
  },
  {
    name: "DeepMind Blog",
    slug: "deepmind-blog",
    homepageUrl: "https://deepmind.google/discover/blog/",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    sourceType: "vendor_blog",
    credibility: 90,
    isActive: true,
  },
  {
    name: "Meta AI Blog",
    slug: "meta-ai-blog",
    homepageUrl: "https://ai.meta.com/blog/",
    feedUrl: "https://ai.meta.com/blog/rss/",
    sourceType: "vendor_blog",
    credibility: 88,
    isActive: true,
  },
  {
    name: "Microsoft AI Blog",
    slug: "microsoft-ai-blog",
    homepageUrl: "https://blogs.microsoft.com/ai/",
    feedUrl: "https://blogs.microsoft.com/ai/feed/",
    sourceType: "vendor_blog",
    credibility: 88,
    isActive: true,
  },
  {
    name: "NVIDIA AI Blog",
    slug: "nvidia-ai-blog",
    homepageUrl: "https://blogs.nvidia.com/blog/category/deep-learning/",
    feedUrl: "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
    sourceType: "vendor_blog",
    credibility: 86,
    isActive: true,
  },
  {
    name: "Hugging Face Blog",
    slug: "hugging-face-blog",
    homepageUrl: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    sourceType: "vendor_blog",
    credibility: 84,
    isActive: true,
  },
  {
    name: "LangChain Blog",
    slug: "langchain-blog",
    homepageUrl: "https://blog.langchain.com/",
    feedUrl: "https://blog.langchain.com/rss/",
    sourceType: "vendor_blog",
    credibility: 82,
    isActive: true,
  },
  {
    name: "Product Hunt AI",
    slug: "product-hunt-ai",
    homepageUrl:
      "https://www.producthunt.com/categories/artificial-intelligence",
    feedUrl: null,
    sourceType: "product_hunt",
    credibility: 72,
    isActive: false,
  },
  {
    name: "Hacker News AI",
    slug: "hacker-news-ai",
    homepageUrl: "https://news.ycombinator.com/",
    feedUrl: null,
    sourceType: "hacker_news",
    credibility: 72,
    isActive: false,
  },
  {
    name: "YC AI",
    slug: "yc-ai",
    homepageUrl: "https://www.ycombinator.com/companies/industry/ai",
    feedUrl: null,
    sourceType: "yc",
    credibility: 80,
    isActive: false,
  },
] as const;

export const initialNewsSources = sourceCandidates.map((source) =>
  CreateNewsSourceSchema.parse(source),
);
