import { CreateNewsSourceSchema } from "@acme/db/schema";

const sourceCandidates = [
  {
    name: "OpenAI News",
    slug: "openai-news",
    homepageUrl: "https://openai.com/news/",
    feedUrl: "https://openai.com/news/rss.xml",
    sourceType: "vendor_blog",
    credibility: 95,
    isActive: true,
  },
  {
    name: "Anthropic News",
    slug: "anthropic-news",
    homepageUrl: "https://www.anthropic.com/news",
    feedUrl: null,
    sourceType: "vendor_blog",
    credibility: 95,
    isActive: false,
  },
  {
    name: "Google AI Blog",
    slug: "google-ai-blog",
    homepageUrl: "https://blog.google/technology/ai/",
    feedUrl: "https://blog.google/technology/ai/rss/",
    sourceType: "vendor_blog",
    credibility: 90,
    isActive: true,
  },
  {
    name: "DeepMind Blog",
    slug: "deepmind-blog",
    homepageUrl: "https://deepmind.google/discover/blog/",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    sourceType: "vendor_blog",
    credibility: 90,
    isActive: true,
  },
  {
    name: "Meta AI Blog",
    slug: "meta-ai-blog",
    homepageUrl: "https://ai.meta.com/blog/",
    feedUrl: null,
    sourceType: "vendor_blog",
    credibility: 88,
    isActive: false,
  },
  {
    name: "Microsoft AI Blog",
    slug: "microsoft-ai-blog",
    homepageUrl: "https://blogs.microsoft.com/ai/",
    feedUrl: "https://www.microsoft.com/en-us/ai/blog/feed/",
    sourceType: "vendor_blog",
    credibility: 88,
    isActive: true,
  },
  {
    name: "NVIDIA AI Blog",
    slug: "nvidia-ai-blog",
    homepageUrl: "https://blogs.nvidia.com/blog/category/deep-learning/",
    feedUrl: "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
    sourceType: "vendor_blog",
    credibility: 86,
    isActive: true,
  },
  {
    name: "Hugging Face Blog",
    slug: "hugging-face-blog",
    homepageUrl: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    sourceType: "vendor_blog",
    credibility: 84,
    isActive: true,
  },
  {
    name: "LangChain Blog",
    slug: "langchain-blog",
    homepageUrl: "https://www.langchain.com/blog",
    feedUrl: "https://www.langchain.com/blog/rss.xml",
    sourceType: "vendor_blog",
    credibility: 82,
    isActive: true,
  },
  {
    name: "TechCrunch AI",
    slug: "techcrunch-ai",
    homepageUrl: "https://techcrunch.com/category/artificial-intelligence/",
    feedUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    sourceType: "rss",
    credibility: 78,
    isActive: true,
  },
  {
    name: "VentureBeat AI",
    slug: "venturebeat-ai",
    homepageUrl: "https://venturebeat.com/category/ai/",
    feedUrl: "https://venturebeat.com/category/ai/feed/",
    sourceType: "rss",
    credibility: 78,
    isActive: true,
  },
  {
    name: "The Verge AI",
    slug: "the-verge-ai",
    homepageUrl: "https://www.theverge.com/ai-artificial-intelligence",
    feedUrl:
      "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    sourceType: "publication",
    credibility: 80,
    isActive: true,
  },
  {
    name: "Ars Technica AI",
    slug: "ars-technica-ai",
    homepageUrl: "https://arstechnica.com/ai/",
    feedUrl: "https://arstechnica.com/ai/feed/",
    sourceType: "publication",
    credibility: 82,
    isActive: true,
  },
  {
    name: "The Decoder",
    slug: "the-decoder",
    homepageUrl: "https://the-decoder.com/",
    feedUrl: "https://the-decoder.com/feed/",
    sourceType: "rss",
    credibility: 78,
    isActive: true,
  },
  {
    name: "MIT News AI",
    slug: "mit-news-ai",
    homepageUrl: "https://news.mit.edu/topic/artificial-intelligence2",
    feedUrl: "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml",
    sourceType: "rss",
    credibility: 88,
    isActive: true,
  },
  {
    name: "arXiv AI/ML",
    slug: "arxiv-ai-ml",
    homepageUrl: "https://arxiv.org/list/cs.AI/recent",
    feedUrl: null,
    sourceType: "research",
    credibility: 86,
    isActive: true,
  },
  {
    name: "Simon Willison LLMs",
    slug: "simon-willison-llms",
    homepageUrl: "https://simonwillison.net/tags/llms/",
    feedUrl: "https://simonwillison.net/tags/llms.atom",
    sourceType: "rss",
    credibility: 82,
    isActive: true,
  },
  {
    name: "Mozilla.ai Blog",
    slug: "mozilla-ai-blog",
    homepageUrl: "https://blog.mozilla.ai/",
    feedUrl: "https://blog.mozilla.ai/rss/",
    sourceType: "vendor_blog",
    credibility: 82,
    isActive: true,
  },
  {
    name: "Import AI",
    slug: "import-ai",
    homepageUrl: "https://importai.substack.com/",
    feedUrl: "https://importai.substack.com/feed",
    sourceType: "research",
    credibility: 84,
    isActive: true,
  },
  {
    name: "Latent Space",
    slug: "latent-space",
    homepageUrl: "https://www.latent.space/",
    feedUrl: "https://www.latent.space/feed",
    sourceType: "rss",
    credibility: 80,
    isActive: true,
  },
  {
    name: "Product Hunt AI",
    slug: "product-hunt-ai",
    homepageUrl:
      "https://www.producthunt.com/categories/artificial-intelligence",
    feedUrl: "https://www.producthunt.com/feed",
    sourceType: "product_hunt",
    credibility: 72,
    isActive: true,
  },
  {
    name: "Hacker News AI",
    slug: "hacker-news-ai",
    homepageUrl: "https://news.ycombinator.com/",
    feedUrl: null,
    sourceType: "hacker_news",
    credibility: 72,
    isActive: true,
  },
  {
    name: "GitHub Trending AI",
    slug: "github-trending-ai",
    homepageUrl: "https://github.com/trending?l=&since=daily",
    feedUrl: null,
    sourceType: "github",
    credibility: 76,
    isActive: true,
  },
  {
    name: "YC AI",
    slug: "yc-ai",
    homepageUrl: "https://www.ycombinator.com/companies/industry/ai",
    feedUrl: null,
    sourceType: "yc",
    credibility: 80,
    isActive: true,
  },
] as const;

export const initialNewsSources = sourceCandidates.map((source) =>
  CreateNewsSourceSchema.parse(source),
);
